name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/userLogo.png
    - lib/assets/sberPrimeIcon.png
    - lib/assets/percentIcon.png
    - lib/assets/disclosure.png
    - lib/assets/ratesIcon.png
    - lib/assets/commissionIcon.png
    - lib/assets/limitIcon.png

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Bold.otf
    - family: SFProText
      fonts:
        - asset: fonts/SFProText/SFProText-Bold.ttf
          weight: 700
        - asset: fonts/SFProText/SFProText-Semibold.ttf
          weight: 600
        - asset: fonts/SFProText/SFProText-Medium.ttf

  